< {%
    request.variables.set("token", "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA1MTY5OTI5fQ.cOaMbheK_gwuxPeGegoJP13S14KB6JtzjRBLUYbU0AQ")
%}
POST http://localhost:3000/api/item/create
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

{
  "title": "仮タイトル1",
  "image": "仮イメージ1",
  "price": "10001",
  "description": "仮説明1",
  "email": "user1@example.com"
}

###
< {%
    request.variables.set("token", "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA1MTY5OTI5fQ.cOaMbheK_gwuxPeGegoJP13S14KB6JtzjRBLUYbU0AQ")
%}
POST http://localhost:3000/api/item/create
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

{
  "title": "仮タイトル2",
  "image": "仮イメージ2",
  "price": "10002",
  "description": "仮説明2",
  "email": "user1@example.com"
}

###
< {%
    request.variables.set("token", "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA1MTY5OTI5fQ.cOaMbheK_gwuxPeGegoJP13S14KB6JtzjRBLUYbU0AQ")
%}
POST http://localhost:3000/api/item/create
Content-Type: application/json;charset=UTF-8
Authorization: Bearer {{token}}

{
  "title": "仮タイトル4",
  "image": "仮イメージ4",
  "price": "10004",
  "description": "仮説明4",
  "email": "user2@example.com"
}

